# Generated by Django 5.0.6 on 2024-07-13 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 13, 23, 5, 2, 89122), verbose_name='date published'),
        ),
    ]
