# Generated by Django 5.0.6 on 2024-09-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='about',
            field=models.TextField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
