# Generated by Django 5.0.6 on 2024-07-13 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_listing_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='pub_date',
        ),
    ]
