# Generated by Django 5.0.6 on 2024-09-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_customuser_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='uploads/users/default_profile_pic.JPEG', upload_to='uploads/users'),
        ),
    ]
