# Generated by Django 5.0.6 on 2024-08-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_listing_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Apparel', 'Apparel'), ('Shoes', 'Shoes'), ('Home & lifestyle', 'Home'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
