# Generated by Django 5.0.6 on 2024-08-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_listing_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('APPAREL', 'Apparel'), ('HOME', 'Home & lifestyle'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
