# Generated by Django 5.0.6 on 2024-10-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_rename_lookingfor_request_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='description',
        ),
        migrations.AddField(
            model_name='request',
            name='title',
            field=models.TextField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
