# Generated by Django 5.1.2 on 2024-10-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_request_description_request_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='description',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
