# Generated by Django 5.1.2 on 2024-11-16 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_request_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('AWAITING_PAYMENT', 'Awaiting Payment'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='INITIATED', max_length=20),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.FloatField()),
                ('comment', models.TextField(max_length=400)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.transaction')),
            ],
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
