# Generated by Django 5.1.2 on 2024-12-13 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_review_receiver_alter_customuser_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='receiver',
            new_name='recipient',
        ),
        migrations.AddField(
            model_name='transaction',
            name='buyer',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
