# Generated by Django 5.1.2 on 2025-01-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_review_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='featured',
            field=models.IntegerField(default=0),
        ),
    ]
